// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2nXBrtgr5ECYqSxDldZxVJbrYbTktxyw',
    appId: '1:659661675866:web:e7ad975666c0e30cace763',
    messagingSenderId: '659661675866',
    projectId: 'scenic-casing-367521',
    authDomain: 'scenic-casing-367521.firebaseapp.com',
    storageBucket: 'scenic-casing-367521.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYNo9SNW3DqckYnfKyzgLuDyOXsuNxu0Q',
    appId: '1:659661675866:android:30bca382db85ea7dace763',
    messagingSenderId: '659661675866',
    projectId: 'scenic-casing-367521',
    storageBucket: 'scenic-casing-367521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwDyQfBdE-sQYyopUpThIjblaUcfR7h04',
    appId: '1:659661675866:ios:8d86429a5428bcbface763',
    messagingSenderId: '659661675866',
    projectId: 'scenic-casing-367521',
    storageBucket: 'scenic-casing-367521.appspot.com',
    androidClientId: '659661675866-umuqotu77qu5onk32l3hrimdkf0p8eir.apps.googleusercontent.com',
    iosClientId: '659661675866-vmrf9eukc39hg2gm93vgnh2hghacbg7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwDyQfBdE-sQYyopUpThIjblaUcfR7h04',
    appId: '1:659661675866:ios:0c42643ecd0fe5a6ace763',
    messagingSenderId: '659661675866',
    projectId: 'scenic-casing-367521',
    storageBucket: 'scenic-casing-367521.appspot.com',
    androidClientId: '659661675866-umuqotu77qu5onk32l3hrimdkf0p8eir.apps.googleusercontent.com',
    iosClientId: '659661675866-tgtq9fo02re77luk8svoqognpkbsk2ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp.RunnerTests',
  );
}
